### PR TITLE
Display prompts to direct user flow on sign in

### LINKED ISSUE #8: 8. As a user, I want to see a welcoming prompt to add my first item if my list is empty to help me get oriented to how the app works
## Summary

When a user starts a new list, they need a little guidance on how to get started. Think through what you'd want to see as a user and make some intentional user experience decisions that will guide our users in confidently adding their very first item. 

## Acceptance criteria
- [ ] The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item
- [ ] The home view, when there are no lists to display, should show a prompt (e.g., a button) for the user to add their first shopping list

### PR DESCRIPTION
**Pull request by tataw-cl**
## Description
Display conditional prompts directing the user what next steps to take when on the 'List' and 'Home' pages. If the user has no lists created, they're prompted to create one on the 'Home' page, then on the 'List' page, there are prompting texts and links to direct the user if they don't have a list yet, or if they haven't added any items to their created shopping lists.
We choose this approach si9nce it was the most intuitive in closing our issue and used conditionals in the 'list' and 'home' pages added to text prompts 

## Related Issue
closes #8 

## Acceptance Criteria

- [x] The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item
- [x] The home view, when there are no lists to display, should show a prompt (e.g., a button) for the user to add their first shopping list

## Type of Changes
`enhancement`

### Before
Before-Home
Before-List

### After
After-Home
After-List

## Testing Steps / QA Criteria

- switch to the branch el-tc-empty-list-prompt by doing `git pull el-tc-empty-list-prompt` in your terminal on the `main` branch
- then type `git checkout el-tc-empty-list-prompt`
- then run `npm start`
- navigate to the `Home` page and `List` page with an email account which has no lists created to see changes

### CODE REVIEW

**Comment by didemydn** [comment]
thanks, guys! It seems working well but I have a question 
this is my home page 

image

There is no list on my home page, and your issue works well, but when I go to the list page, I see the items and cannot navigate the manage list. Also, I deleted all my lists from the Firebase store.  why do I see the search items in my list view?

image

**Comment by GrannyYetta** [comment]
Hi Eva and Tataw, 

thank you for the PR. 

I am not getting the prompt in my home view:

Captura de pantalla 2024-09-07 a la(s) 20 34 59


I am also not getting a prompt in my List view:

Captura de pantalla 2024-09-07 a la(s) 20 36 05


Could this be specific to my browser?

**Comment by tataw-cl** [comment]
Thanks for the comments guys, I believe Eva has fixed the issue more. And as for @GrannyYetta, I think the issue should be your browser I guess, cause it works well overall on our side

**Review by Amaka202 — APPROVED** [review]
Weldone guys! your feature works well!✅💥

**Pull request merged**
